# Generated by Django 4.1.2 on 2022-11-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=1000)),
                ("mvideo_price", models.IntegerField(default=0)),
                ("eldorado_price", models.IntegerField(default=0)),
            ],
        ),
    ]
